import Head from 'next/head'
import styles from './styles.module.scss'
import { useEffect, useState } from 'react'
import { followUsersInterface } from './api/follow-users'
import { followUsersType } from '@/interfaces/dataRequests'
import { useRouter } from 'next/router'
import axios from 'axios'
import Cookies from 'js-cookie'


export default function Home() {

  const [data, setData] = useState<followUsersType>()
  const router = useRouter()

  useEffect(() => {
    axios.post("/api/follow-users", {}, {
      headers: {
        Authorization: Cookies.get("token") || ""
      }
    }).then((reqData) => {
      const request: followUsersInterface = reqData.data
      return request.auth.isLogged && setData(request.data)
    })

  }, [router])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>

        {data?.map((usr, i) => <div key={i}>{usr.name}</div>)}


      </main>
    </>
  )
}
